server:
  port: 8083
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: OrderSvc
  sql:
    init:
      continue-on-error: true
      mode: always
database:
  type: SQL
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 10
  instance:
    hostname: localhost
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/yitong
    name: yitong
    username: postgres
    driver-class-name: org.postgresql.Driver
---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}
      sql:
        instance-connection-name: ${GCP_SQL_INSTANCE_CONNECTION_NAME}
        database-name: ${GCP_SQL_DATABASE_NAME}