spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  sql:
    init:
      continue-on-error: true
      mode: always
port:
  admin: 8081
  auth: 8082
  inventory: 8083
  order: 8084
  product: 8085
database:
  type: SQL
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/yitong
    name: yitong
    username: postgres
    driver-class-name: org.postgresql.Driver
---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}
      credentials: ${GCP_CREDENTIALS}
      sql:
        database-type: postgresql
        instance-connection-name: ${GCP_SQL_INSTANCE_CONNECTION_NAME}
        database-name: ${GCP_SQL_DATABASE_NAME}
        username: ${GCP_SQL_USERNAME}
        password: ${GCP_SQL_PASSWORD}